trayer -l \
    --edge top \
    --align right \
    --margin 5 \
    --widthtype request \
    --padding 8 \
    --distance 1 \
    --iconspacing 6 \
    --SetDockType true \
    --SetPartialStrut true \
    --expand true \
    --transparent true \
    --alpha 0 \
    --tint 0x232634 \
    --height 33