mod = "mod4"
alt="mod1"
terminal_kitty = "kitty"
terminal = "wezterm"
mymenu = "rofi -show drun"
browser = "google-chrome-stable"
files = "nautilus"
discord = "webcord"
todoist = "flatpak run com.todoist.Todoist"
screenie = "flameshot gui"

