#!/usr/bin/env bash


# sed -i -E 's/(class|interface|enum|record) MarkerInterface\s/\1 MarkerInterface /g' /home/serhii/tools/java-test-projs/Employee-Management-Sys/EmployeeManagementSystem/src/main/java/com/example/EmployeeManagementSystem/service/employe/MarkerInterface.java
# rg --color=never -l 'import\s+com\.example\.EmployeeManagementSystem\.service\.MarkerInterface' /home/serhii/tools/java-test-projs/Employee-Management-Sys/EmployeeManagementSystem | xargs sed -i -E 's/([[:space:],;(}<])MarkerInterface([[:space:],;(}\.>])/\1MarkerInterface\2/g' || echo 'skipped'
# rg --color=never -l 'com\.example\.EmployeeManagementSystem\.service\.MarkerInterface' /home/serhii/tools/java-test-projs/Employee-Management-Sys/EmployeeManagementSystem | xargs sed -i -E 's/com\.example\.EmployeeManagementSystem\.service\.MarkerInterface([;.$"]|$)/com.example.EmployeeManagementSystem.service.employe.MarkerInterface\1/g' || echo 'skipped'
# sed -i -E 's/package\s+com\.example\.EmployeeManagementSystem\.service;/package com.example.EmployeeManagementSystem.service.employe;/g' /home/serhii/tools/java-test-projs/Employee-Management-Sys/EmployeeManagementSystem/src/main/java/com/example/EmployeeManagementSystem/service/employe/MarkerInterface.java
# "/home/serhii/dotfiles/work/java/remane/fix-old-imports.sh" "/home/serhii/tools/java-test-projs/Employee-Management-Sys/EmployeeManagementSystem/src/main/java/com/example/EmployeeManagementSystem/service" "com.example.EmployeeManagementSystem.service" "com.example.EmployeeManagementSystem.service.employe" "/home/serhii/tools/java-test-projs/Employee-Management-Sys/EmployeeManagementSystem/src/main/java/com/example/EmployeeManagementSystem/service/employe/MarkerInterface.java" "MarkerInterface" "MarkerInterface"
# rg --color=never -l 'com\/example\/EmployeeManagementSystem\/service\/MarkerInterface' /home/serhii/tools/java-test-projs/Employee-Management-Sys/EmployeeManagementSystem | xargs sed -i -E 's/com\/example\/EmployeeManagementSystem\/service\/MarkerInterface([;."]|$)/com\/example\/EmployeeManagementSystem\/service\/employe\/MarkerInterface\1/g' || echo 'skipped'

# sed -i -E 's/(class|interface|enum|record) JustUselesInterface\s/\1 JustUselesInterface /g' /home/serhii/tools/java-test-projs/Employee-Management-Sys/EmployeeManagementSystem/src/main/java/com/example/EmployeeManagementSystem/service/employe/JustUselesInterface.java
# rg --color=never -l 'import\s+com\.example\.EmployeeManagementSystem\.service\.JustUselesInterface' /home/serhii/tools/java-test-projs/Employee-Management-Sys/EmployeeManagementSystem | xargs sed -i -E 's/([[:space:],;(}<])JustUselesInterface([[:space:],;(}\.>])/\1JustUselesInterface\2/g' || echo 'skipped'
# rg --color=never -l 'com\.example\.EmployeeManagementSystem\.service\.JustUselesInterface' /home/serhii/tools/java-test-projs/Employee-Management-Sys/EmployeeManagementSystem | xargs sed -i -E 's/com\.example\.EmployeeManagementSystem\.service\.JustUselesInterface([;.$"]|$)/com.example.EmployeeManagementSystem.service.employe.JustUselesInterface\1/g' || echo 'skipped'
# sed -i -E 's/package\s+com\.example\.EmployeeManagementSystem\.service;/package com.example.EmployeeManagementSystem.service.employe;/g' /home/serhii/tools/java-test-projs/Employee-Management-Sys/EmployeeManagementSystem/src/main/java/com/example/EmployeeManagementSystem/service/employe/JustUselesInterface.java
# "/home/serhii/dotfiles/work/java/remane/fix-old-imports.sh" "/home/serhii/tools/java-test-projs/Employee-Management-Sys/EmployeeManagementSystem/src/main/java/com/example/EmployeeManagementSystem/service" "com.example.EmployeeManagementSystem.service" "com.example.EmployeeManagementSystem.service.employe" "/home/serhii/tools/java-test-projs/Employee-Management-Sys/EmployeeManagementSystem/src/main/java/com/example/EmployeeManagementSystem/service/employe/JustUselesInterface.java" "JustUselesInterface" "JustUselesInterface"
# rg --color=never -l 'com\/example\/EmployeeManagementSystem\/service\/JustUselesInterface' /home/serhii/tools/java-test-projs/Employee-Management-Sys/EmployeeManagementSystem | xargs sed -i -E 's/com\/example\/EmployeeManagementSystem\/service\/JustUselesInterface([;."]|$)/com\/example\/EmployeeManagementSystem\/service\/employe\/JustUselesInterface\1/g' || echo 'skipped'

# sed -i -E 's/(class|interface|enum|record) ServiceEmployeeIn\s/\1 ServiceEmployeeIn /g' /home/serhii/tools/java-test-projs/Employee-Management-Sys/EmployeeManagementSystem/src/main/java/com/example/EmployeeManagementSystem/service/employe/ServiceEmployeeIn.java
# rg --color=never -l 'import\s+com\.example\.EmployeeManagementSystem\.service\.ServiceEmployeeIn' /home/serhii/tools/java-test-projs/Employee-Management-Sys/EmployeeManagementSystem | xargs sed -i -E 's/([[:space:],;(}<])ServiceEmployeeIn([[:space:],;(}\.>])/\1ServiceEmployeeIn\2/g' || echo 'skipped'
# rg --color=never -l 'com\.example\.EmployeeManagementSystem\.service\.ServiceEmployeeIn' /home/serhii/tools/java-test-projs/Employee-Management-Sys/EmployeeManagementSystem | xargs sed -i -E 's/com\.example\.EmployeeManagementSystem\.service\.ServiceEmployeeIn([;.$"]|$)/com.example.EmployeeManagementSystem.service.employe.ServiceEmployeeIn\1/g' || echo 'skipped'
# sed -i -E 's/package\s+com\.example\.EmployeeManagementSystem\.service;/package com.example.EmployeeManagementSystem.service.employe;/g' /home/serhii/tools/java-test-projs/Employee-Management-Sys/EmployeeManagementSystem/src/main/java/com/example/EmployeeManagementSystem/service/employe/ServiceEmployeeIn.java
# "/home/serhii/dotfiles/work/java/remane/fix-old-imports.sh" "/home/serhii/tools/java-test-projs/Employee-Management-Sys/EmployeeManagementSystem/src/main/java/com/example/EmployeeManagementSystem/service" "com.example.EmployeeManagementSystem.service" "com.example.EmployeeManagementSystem.service.employe" "/home/serhii/tools/java-test-projs/Employee-Management-Sys/EmployeeManagementSystem/src/main/java/com/example/EmployeeManagementSystem/service/employe/ServiceEmployeeIn.java" "ServiceEmployeeIn" "ServiceEmployeeIn"
# rg --color=never -l 'com\/example\/EmployeeManagementSystem\/service\/ServiceEmployeeIn' /home/serhii/tools/java-test-projs/Employee-Management-Sys/EmployeeManagementSystem | xargs sed -i -E 's/com\/example\/EmployeeManagementSystem\/service\/ServiceEmployeeIn([;."]|$)/com\/example\/EmployeeManagementSystem\/service\/employe\/ServiceEmployeeIn\1/g' || echo 'skipped'

# sed -i -E 's/(class|interface|enum|record) ServiceEmployee\s/\1 ServiceEmployee /g' /home/serhii/tools/java-test-projs/Employee-Management-Sys/EmployeeManagementSystem/src/main/java/com/example/EmployeeManagementSystem/service/employe/ServiceEmployee.java
# rg --color=never -l 'import\s+com\.example\.EmployeeManagementSystem\.service\.ServiceEmployee' /home/serhii/tools/java-test-projs/Employee-Management-Sys/EmployeeManagementSystem | xargs sed -i -E 's/([[:space:],;(}<])ServiceEmployee([[:space:],;(}\.>])/\1ServiceEmployee\2/g' || echo 'skipped'
# rg --color=never -l 'com\.example\.EmployeeManagementSystem\.service\.ServiceEmployee' /home/serhii/tools/java-test-projs/Employee-Management-Sys/EmployeeManagementSystem | xargs sed -i -E 's/com\.example\.EmployeeManagementSystem\.service\.ServiceEmployee([;.$"]|$)/com.example.EmployeeManagementSystem.service.employe.ServiceEmployee\1/g' || echo 'skipped'
# sed -i -E 's/package\s+com\.example\.EmployeeManagementSystem\.service;/package com.example.EmployeeManagementSystem.service.employe;/g' /home/serhii/tools/java-test-projs/Employee-Management-Sys/EmployeeManagementSystem/src/main/java/com/example/EmployeeManagementSystem/service/employe/ServiceEmployee.java
# "/home/serhii/dotfiles/work/java/remane/fix-old-imports.sh" "/home/serhii/tools/java-test-projs/Employee-Management-Sys/EmployeeManagementSystem/src/main/java/com/example/EmployeeManagementSystem/service" "com.example.EmployeeManagementSystem.service" "com.example.EmployeeManagementSystem.service.employe" "/home/serhii/tools/java-test-projs/Employee-Management-Sys/EmployeeManagementSystem/src/main/java/com/example/EmployeeManagementSystem/service/employe/ServiceEmployee.java" "ServiceEmployee" "ServiceEmployee"
# rg --color=never -l 'com\/example\/EmployeeManagementSystem\/service\/ServiceEmployee' /home/serhii/tools/java-test-projs/Employee-Management-Sys/EmployeeManagementSystem | xargs sed -i -E 's/com\/example\/EmployeeManagementSystem\/service\/ServiceEmployee([;."]|$)/com\/example\/EmployeeManagementSystem\/service\/employe\/ServiceEmployee\1/g' || echo 'skipped'