#!/usr/bin/env bash

# killall trayer
# killall xmobar

# xmobar ~/dotfiles/xmobar/.config/xmobar/xmobarrc.hs

trayer \
    --edge top \
    --align right \
    --margin 5 \
    --widthtype request \
    --padding 8 \
    --iconspacing 6 \
    --SetDockType true \
    --SetPartialStrut true \
    --expand true \
    --transparent true \
    --alpha 0 \
    --tint 0x5f5f5f \
    --height 30