# [[shades]]
# name = "vibrance"
# default = true

[[shades]]
name = "blue-light-filter"
start_time = 19:00:00
end_time = 06:00:00

# hyprshade install
# systemctl --user enable --now hyprshade.timer (systemctl --user disable hyprshade.timer, systemctl --user stop hyprshade.timer)