#!/usr/bin/env bash
# Display disk usage for both `/` and `/home`.

case $BLOCK_BUTTON in
    1) setsid --fork foot --app-id=com.term.float.disc_ugd -e gdu ~ ;;
    6) setsid --fork foot -e nvim "$0" ;;
        # *) notify-send "not action on: button -- $BLOCK_BUTTON" ;;
esac

. "$HOME"/dotfiles/scripts/dwl/colorscheme
disk_usage=$(df -B 1K | grep '/home' | tr -s ' ' | cut -d' ' -f5 | tr -d '%')

echo " ^fg(e5c890) ^fg($FG_COLOR) $disk_usage^fg(6272a4)% ^fg(6272a4)SSD $SPLIT"
