#!/usr/bin/env bash
# Display currently playing music.

case "$BLOCK_BUTTON" in
    1) playerctl play-pause ;;
    2) playerctl stop ;;
    3) setsid --fork foot --app-id com.scratchpad.music /home/serhii/.cargo/bin/rmpc ;;
    4) playerctl next ;;
    5) playerctl previous ;;
    6) setsid --fork foot -e nvim "$0" ;;
        # *) notify-send "not action on: button -- $BLOCK_BUTTON" ;;
esac

set -- --player=spotify,mpv,%any
icon="󰝚"
paused_icon=""
if status="$(playerctl "$@" status 2>&1)" && [ "$status" != "Stopped" ]; then
    [ "$status" = "Paused" ] && icon="$paused_icon"

    song="$(playerctl "$@" metadata --format="{{title}} - {{artist}}")"
else
    [ "$(mpc status "%state%")" = "paused" ] && icon="$paused_icon"

    song="$(mpc current --format="%title%[ - %artist%]")"
fi

[ -z "$song" ] && exit

echo "$icon $song"