#!/usr/bin/env bash

case "$BLOCK_BUTTON" in
    1) brave https://sinoptik.ua/pohoda/vinnytsia ;;
    3) setsid --fork gnome-weather ;;
    6) setsid --fork foot -e nvim "$0" ;;
        # *) notify-send "not action on: button -- $BLOCK_BUTTON" ;;
esac

. "$HOME"/dotfiles/scripts/dwl/colorscheme
. "$HOME"/dotfiles/scripts/wmscripts/status-bar/shared-openweather.cached

# echo "^fg(6272a4)$weather_title ^fg($icon_color)$icon ^fg($FG_COLOR)${temperature}^fg(6272a4)°C$SPLIT"
#echo "^fg($icon_color)$icon ^fg($FG_COLOR)${temperature}^fg(6272a4)°C$SPLIT"
# echo "^fg($icon_color)$icon ^fg($FG_COLOR)${temperature}^fg($units_color)°C$SPLIT_LEFT"

icon=$(get_emoji "$WEATHER_ICON")
icon_color=$(get_emoji_color "$WEATHER_ICON")
icon_color="${icon_color#\#}"
units_color="${units_color#\#}"
temperature=$TEMPERATURE
echo " ^fg($icon_color)$icon^fg($FG_COLOR)${temperature}^fg($units_color)°C $SPLIT_LEFT"
