#!/usr/bin/env bash

monitor_names=($(bspc query -M --names | grep '^HDMI'))
if [ ${#monitor_names[@]} -gt 1 ]; then
    bspc monitor "${monitor_names[0]}" -d 1 2 3 4 5 6 7 8
    bspc monitor "${monitor_names[1]}" -d 9
else
    bspc monitor "${monitor_names[0]}" -d 1 2 3 4 5 6 7 8 9
fi

bspc config pointer_modifier mod4
bspc config border_width         5
bspc config window_gap          12

bspc config single_monocle        false
bspc config focus_follows_pointer true # Focus the window under the pointer.
bspc config click_to_focus        false
#bspc config pointer_follows_focus    true
#bspc config pointer_follows_monitor  true
bspc config remove_disabled_monitors  false
bspc config remove_unplugged_monitors false

bspc config split_ratio          0.55
bspc config borderless_monocle   false # Remove borders of tiled windows for the monocle desktop layout.
bspc config gapless_monocle      false # Set the desktop layout to monocle if there’s only one tiled window in the tree.

#### Mouse #### -  Action performed when pressing pointer_modifier + button<n>.
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action3 resize_corner

#### BSPWM coloring ####
bspc config focused_border_color    "#5e81ac" # "#00bcd4"
bspc config presel_feedback_color   "#5e81ac"
bspc config normal_border_color     "#2E3134"

#Window rules
bspc rule -a "SimpleScreenRecorder" state=floating
bspc rule -a "Pavucontrol" state=floating
bspc rule -a "Firefox" desktop=^2
bspc rule -a "Thunar" desktop=^3
bspc rule -a "kdenlive" desktop=^5
bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

#bspc rule -a "$name" --one-shot state=floating sticky=on hidden=on
# bspc rule -a com.scratchpad.yazi state=floating rectangle=1280x800+380+170
# bspc rule -a telegram-desktop state=floating rectangle=1280x800+380+170
# bspc rule -a org.gnome.Nautilus state=floating rectangle=1280x800+380+170
#
# # music
# bspc rule -a crx_cinhimbnkkaeohfgghhklpknlkffjgod state=floating rectangle=1280x800+380+170
# # chat
# bspc rule -a crx_mdpkiolbdkhdjpekfbkbmhigcaggjagi state=floating rectangle=1280x800+380+170
# # monkeytype
# bspc rule -a crx_picebhhlijnlefeleilfbanaghjlkkna state=floating rectangle=1280x800+380+170


# bspc rule -a com.ghostty.group01:ghostty state=floating rectangle=1280x800+380+170

# WM_CLASS(STRING) = "ghostty", "com.ghostty.group01"
# by instant
# bspc rule -a ghostty state=floating
#
# by class
# bspc rule -a com.ghostty.group01 state=floating
#
# by both
# bspc rule -a com.ghostty.group01:ghostty state=floating

# Rules examples:
# #bspc rule -a TelegramDesktop state=floating follow=off rectangle=420x900+750+90
# bspc rule -a TelegramDesktop state=floating follow=off
# bspc rule -a firefox state=floating rectangle=1600x900+160+90 desktop='^1'
# bspc rule -a Lutris state=floating follow=off rectangle=1200x700+360+190 desktop='^6'
# bspc rule -a mpv state=floating rectangle=800x450+560+315 follow=off
# bspc rule -a dmenu rectangle=900x22+610+90
# bspc rule -a Viewnior rectangle=1350x900+285+90 state=floating
# bspc rule -a Inkscape desktop='^3'
# bspc rule -a Blender desktop='^2'
#
# For scratchpads:
# bspc rule -a mysp state=floating rectangle=1280x800+380+170
# bspc rule -a scp2 state=floating rectangle=1280x800+380+170
# bspc rule -a pulse state=floating rectangle=1280x800+380+170
# bspc rule -a music state=floating rectangle=1280x800+380+170
# bspc rule -a news state=floating rectangle=1280x800+380+170
# bspc rule -a ranger state=floating rectangle=1280x800+380+170