#!/usr/bin/env bash

monitor_names=($(bspc query -M --names | grep '^HDMI'))
if [ ${#monitor_names[@]} -gt 1 ]; then
    bspc monitor "${monitor_names[0]}" -d 1 2 3 4 5 6 7 8
    bspc monitor "${monitor_names[1]}" -d 9
else
    bspc monitor "${monitor_names[0]}" -d 1 2 3 4 5 6 7 8 9
fi

bspc config border_width         5
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

# bspc config focus_follows_pointer true
#
# bspc rule -a mysp state=floating rectangle=1280x800+380+170
# bspc rule -a scp2 state=floating rectangle=1280x800+380+170
# bspc rule -a pulse state=floating rectangle=1280x800+380+170
# bspc rule -a music state=floating rectangle=1280x800+380+170
# bspc rule -a news state=floating rectangle=1280x800+380+170
# bspc rule -a ranger state=floating rectangle=1280x800+380+170
#