#!/usr/bin/env bash

monitor_names=($(bspc query -M --names | grep '^HDMI'))
if [ ${#monitor_names[@]} -gt 1 ]; then
    bspc monitor "${monitor_names[0]}" -d 1 2 3 4 5 6 7 8
    bspc monitor "${monitor_names[1]}" -d 9
else
    bspc monitor "${monitor_names[0]}" -d 1 2 3 4 5 6 7 8 9
fi

bspc config border_width         5
bspc config window_gap          12

bspc config single_monocle        false
bspc config focus_follows_pointer true
bspc config click_to_focus        false
#bspc config pointer_follows_focus    true
#bspc config pointer_follows_monitor  true
# bspc config remove_disabled_monitors  true
# bspc config remove_unplugged_monitors  true

bspc config split_ratio          0.55
bspc config borderless_monocle   false
bspc config gapless_monocle      false

##Color theme (based on Adapta Dark colors)
bspc config focused_border_color "#00bcd4"
bspc config normal_border_color "#2E3134"
bspc config presel_feedback_color "#4B4F51"

#Window rules
bspc rule -a "SimpleScreenRecorder" state=floating
bspc rule -a "Pavucontrol" state=floating
bspc rule -a "Firefox" desktop=^2
bspc rule -a "Thunar" desktop=^3
bspc rule -a "kdenlive" desktop=^5
bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

# Progress:
# bspc config focus_follows_pointer true
#
# bspc rule -a mysp state=floating rectangle=1280x800+380+170
# bspc rule -a scp2 state=floating rectangle=1280x800+380+170
# bspc rule -a pulse state=floating rectangle=1280x800+380+170
# bspc rule -a music state=floating rectangle=1280x800+380+170
# bspc rule -a news state=floating rectangle=1280x800+380+170
# bspc rule -a ranger state=floating rectangle=1280x800+380+170
#

# #bspc config border_radius                8
# bspc config border_width                  2
# bspc config window_gap                    10
# bspc config top_padding                   20
# bspc config bottom_padding                0
# bspc config left_padding                  0
# bspc config right_padding                 0
# bspc config single_monocle                false
# bspc config click_to_focus                true
# bspc config split_ratio                   0.50
# bspc config borderless_monocle            true
# bspc config gapless_monocle               true
# bspc config focus_by_distance             true
# bspc config focus_follows_pointer         true
# bspc config history_aware_focus           true
# bspc config remove_disabled_monitors      true
# bspc config merge_overlapping_monitors    true
# bspc config pointer_modifier mod4
# bspc config pointer_action1 move
# bspc config pointer_action2 resize_side
# bspc config pointer_action3 resize_corner
#
# #### BSPWM coloring ####
# bspc config normal_border_color           "#4c566a"
# bspc config active_border_color	      "#1e1e1e"
# bspc config focused_border_color	      "#5e81ac"
# bspc config presel_feedback_color	      "#5e81ac"
# bspc config urgent_border_color 	      "#dd2727"
#
#
# bspc rule -a Gimp desktop='^8' state=floating follow=on
# bspc rule -a Chromium desktop='^2'
# bspc rule -a mplayer2 state=floating
# bspc rule -a Kupfer.py focus=on
# bspc rule -a Screenkey manage=off
#
# # ------------------------
#
# bspc config border_width         0
# bspc config window_gap           10
# bspc config split_ratio          0.5
# bspc config focus_follows_pointer true
# bspc config presel_feedback_color "#d4be98"
#
# bspc rule -a mysp state=floating rectangle=1280x800+380+170
# bspc rule -a scp2 state=floating rectangle=1280x800+380+170
# bspc rule -a pulse state=floating rectangle=1280x800+380+170
# bspc rule -a music state=floating rectangle=1280x800+380+170
# bspc rule -a news state=floating rectangle=1280x800+380+170
# bspc rule -a ranger state=floating rectangle=1280x800+380+170
# # Theme concept from https://github.com/Sinomor/dots/tree/main
#
#
# # ------------------------------
#
# #bspc rule -a TelegramDesktop state=floating follow=off rectangle=420x900+750+90
# bspc rule -a TelegramDesktop state=floating follow=off
# bspc rule -a firefox state=floating rectangle=1600x900+160+90 desktop='^1'
# bspc rule -a Lutris state=floating follow=off rectangle=1200x700+360+190 desktop='^6'
# bspc rule -a mpv state=floating rectangle=800x450+560+315 follow=off
# bspc rule -a dmenu rectangle=900x22+610+90
# bspc rule -a Viewnior rectangle=1350x900+285+90 state=floating
# bspc rule -a Inkscape desktop='^3'
# bspc rule -a Blender desktop='^2'
#
# bspc monitor -d 󰖟 󰳫        󰊗 
#
# bspc config border_width         1
# bspc config window_gap          10
#
# bspc config normal_border_color "#23252e"
# bspc config active_border_color "#23252e"
# bspc config focused_border_color "#f9f8fe"
# bspc config presel_feedback_color "#23252e"
#
# bspc config split_ratio          0.5
#
# bspc config focus_follows_pointer true
# bspc config pointer_modifier	super
#
# bspc config single_monocle	     true
# bspc config borderless_monocle   true
# bspc config gapless_monocle      false
# bspc config paddingless_monocle	 true



