#!/usr/bin/env bash

case "$1" in
    "yazi")
        class_name="com.scratchpad.yazi"
        run_cmd="ghostty --class=com.scratchpad.yazi -e yazi"
        ;;
    "nautilus")
        class_name="org.gnome.Nautilus"
        run_cmd="nautilus"
        ;;
    "telegram")
        # WM_CLASS(STRING) = "telegram-desktop", "TelegramDesktop"
        class_name="TelegramDesktop"
        run_cmd="telegram-desktop"
        ;;
    "crx_cinhimbnkkaeohfgghhklpknlkffjgod")
        # youtube_music
        run_cmd="brave --profile-directory=Default --app-id=cinhimbnkkaeohfgghhklpknlkffjgod"
        ;;
    "crx_mdpkiolbdkhdjpekfbkbmhigcaggjagi")
        # WM_CLASS(STRING) = "crx_mdpkiolbdkhdjpekfbkbmhigcaggjagi", "Brave-browser"
        # google_chat
        run_cmd="brave --profile-directory=Default --app-id=mdpkiolbdkhdjpekfbkbmhigcaggjagi"
        ;;
    "crx_picebhhlijnlefeleilfbanaghjlkkna")
        # monkey_type
        run_cmd="brave --profile-directory=Default --app-id=picebhhlijnlefeleilfbanaghjlkkna"
        ;;
    *)
        echo "$1 - is not supported"
        exit 1
        ;;
esac

filename=/tmp/"$class_name"

bspc_write_nodeid() {
    sleep 0.3s
    for id in $(bspc query -d focused -N -n '.floating.sticky.hidden'); do
        bspc query --node $id -T | command grep -q $class_name && { echo $id > $filename; flag=true; break; }
    done

    sleep 0.1s
    # while true; do
    #     flag=false
    #     for id in $(bspc query -d focused -N -n '.floating.sticky.hidden'); do
    #         bspc query --node $id -T | command grep -q $class_name && { echo $id > $filename; flag=true; break; }
    #     done
    #
    #     [[ "$flag" == "true" ]] && break
    #     sleep 0.1s
    # done
    # echo 1
}

hide_all_except_current() {
    for id in $(bspc query -d focused -N -n '.floating.sticky.!hidden')
    do
        bspc query --node $id -T | command grep -qv $class_name && bspc node $id --flag hidden=on
    done
}

toggle_hidden() {
    [ -e "$filename" ] || exit 1
    hide_all_except_current
    id=$(<"$filename")
    bspc node "$id" --flag hidden -f
}

calc_bc() {
    echo "scale=0; ($1)/1" | bc -l
}

# Try to locate a window with the given class.
WIN_ID=$(xdotool search --class "$class_name" 2>/dev/null | head -n 1)

# if ! command ps -ef | command grep -q "[c]lass=$class_name"; then
if [ -z "$WIN_ID" ]; then

    screen_width=3840
    screen_height=2160

    factor_width=0.75
    factor_height=0.8

    window_width=$(calc_bc "$screen_width * $factor_width")
    window_height=$(calc_bc "$screen_height * $factor_height")

    window_x=$(calc_bc "$screen_width / 2 - $window_width / 2")
    window_y=$(calc_bc "$screen_height / 2 - $window_height / 2")
    rectangle_val="$window_width"x"$window_height"+"$window_x"+"$window_y"
    # echo rectangle_val=$rectangle_val

    bspc rule -a "$class_name" --one-shot state=floating sticky=on hidden=on rectangle="$rectangle_val"

    bash -c "$run_cmd" > /dev/null 2>&1 &

    dunstify "Scratch: starting $class_name"
    bspc_write_nodeid
    toggle_hidden
else
    toggle_hidden
fi