return {
    "nvim-treesitter/nvim-treesitter",
    opts = {
        ensure_installed = {
            "bash",
            "html",
            "javascript",
            "json",
            "lua",
            "markdown",
            "markdown_inline",
            "python",
            "query",
            "regex",
            "tsx",
            "typescript",
            "vim",
            "yaml",
            "java",
            "kotlin",
            "xml",
            "strace",
            "groovy",
            "terraform",
            "haskell",
            -- "css",
            -- "latex",
            -- "norg",
            -- "scss",
            -- "svelte",
            -- "typst",
            -- "vue",
        },
        indent = { enable = true, disable = { "java" } },
    },
    {
        "nvim-treesitter/nvim-treesitter-context",
        enabled = false,
    },
}