return {}
-- return {
--     "tpope/vim-fugitive",
--     cmd = { "Git", "G" },
-- }

-- return {
--     "tpope/vim-fugitive",
--     -- enabled = false,
--     cmd = { "Git", "G" },
--     config = function()
--         -- Helpful keymaps for Git operations
--         vim.keymap.set("n", "<leader>gs", ":Git<CR>")
--         vim.keymap.set("n", "<leader>gd", ":Gdiffsplit<CR>")
--         vim.keymap.set("n", "<leader>gc", ":Git commit<CR>")
--         vim.keymap.set("n", "<leader>gb", ":Git blame<CR>")
--         vim.keymap.set("n", "<leader>gm", ":Git mergetool<CR>")
--
--         -- Improve diff experience
--         vim.opt.diffopt:append("algorithm:patience")
--         vim.opt.diffopt:append("indent-heuristic")
--
--         -- Quick conflict resolution
--         vim.keymap.set("n", "<leader>gj", ":diffget //3<CR>") -- get from right
--         vim.keymap.set("n", "<leader>gf", ":diffget //2<CR>") -- get from left
--     end,
-- }
