#!/usr/bin/env bash

PLUGIN_DIR="$CONFIG_DIR/plugins"
ITEM_DIR="$CONFIG_DIR/items" # Directory where the items are configured

sketchybar --bar position=top height=25 blur_radius=30 color=0x40232634

default=(
    padding_left=5
    padding_right=5
    icon.font="CaskaydiaCove Nerd Font:Bold:17.0"
    label.font="CaskaydiaCove Nerd Font:Bold:16.0"
    icon.color=0xff94928F
    label.color=0xff94928F
    icon.padding_left=4
    #icon.padding_right=4
    label.padding_left=4
    label.padding_right=4
    label.y_offset=1
    icon.y_offset=1
)
sketchybar --default "${default[@]}"

##### Adding Left Items #####
source "$ITEM_DIR/front_app.sh"

##### Adding Center Items #####
source "$ITEM_DIR/date.sh"
source "$ITEM_DIR/aerospace.sh"
source "$ITEM_DIR/clock.sh"

##### Adding Right Items #####
source "$ITEM_DIR/battery.sh"
source "$ITEM_DIR/volume.sh"
source "$ITEM_DIR/input.sh"

sketchybar --hotload on
sketchybar --update