#!/usr/bin/env bash

LOCK="🔒 Lock"
LOGOUT="🚪 Logout"
SUSPEND="⏸ Sleep"
REBOOT="🔁 Restart"
SHUTDOWN="⛔ Shutdown"

choice=$(printf "$LOCK\n$LOGOUT\n$SUSPEND\n$REBOOT\n$SHUTDOWN" | rofi -dmenu)
case "$choice" in
    "$LOCK") sh $HOME/dotfiles/scripts/screen-lock ;;
    "$LOGOUT") pkill -KILL -u "$USER" ;;
    "$SUSPEND") systemctl suspend && sh $HOME/dotfiles/scripts/screen-lock ;;
    "$REBOOT") systemctl reboot ;;
    "$SHUTDOWN") systemctl poweroff ;;
esac
