k9s:
  liveViewAutoRefresh: false
  screenDumpDir: $HOME/.local/state/k9s/screen-dumps
  refreshRate: 2
  maxConnRetry: 5
  readOnly: false
  noExitOnCtrlC: false
  ui:
    enableMouse: false
    headless: false
    logoless: false
    crumbsless: false
    reactive: false
    noIcons: false
    defaultsToFullScreen: false
    skin: stock
    #skin: catppuccin-mocha
    #skin: catppuccin-macchiato
    #skin: catppuccin-frappe
    #skin: catppuccin-latte
    #skin: catppuccin-mocha-transparent
    ##skin: catppuccin-macchiato-transparent
    #skin: catppuccin-frappe-transparent
    #skin: catppuccin-latte-transparent
  skipLatestRevCheck: false
  disablePodCounting: false
  shellPod:
    image: busybox:1.35.0
    namespace: default
    limits:
      cpu: 100m
      memory: 100Mi
  imageScans:
    enable: false
    exclusions:
      namespaces: []
      labels: {}
  logger:
    tail: 100
    buffer: 10000
    sinceSeconds: -1
    textWrap: false
    showTime: false
  thresholds:
    cpu:
      critical: 90
      warn: 70
    memory:
      critical: 90
      warn: 70
