-- Hyprland Lua configuration (0.55+)
-- Refer to the wiki for more information: https://wiki.hypr.land/Configuring/Start/
require("module/monitors")
require("module/autostart")
require("module/general")
require("module/input")
require("module/keybindings")
require("module/rules")
require("module/scratchpad")
require("module/env")